# Base configs
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Shots by Satyam"
subtitle: "A chapter from my life"
author:  "Satyam Patil"
header:
 title: "Shots"
 subtitle: "by Satyam Patil"
footer:
 name: "Hello World! 👋'"
 bio: "photograph. Basically, following my curiosity and trying to find my purpose on this beautiful big blue ball. Learn more at: https://swiftlysingh.com"
social_urls:
  instagram: "https://www.instagram.com/satyamawk/"
  # twitter: "https://twitter.com/pushpinderpal_"
